# Generated by Django 2.2.6 on 2019-11-05 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_remove_answer_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionsLikes',
            new_name='QuestionLikes',
        ),
        migrations.RenameField(
            model_name='questionlikes',
            old_name='Questions',
            new_name='Question',
        ),
    ]
