# Generated by Django 2.2.6 on 2019-11-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191105_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlikes',
            old_name='Question',
            new_name='question',
        ),
    ]
